#!/bin/bash
set -evx

module purge
module load git

git_version=$(git rev-parse --verify HEAD)
logname="hackathon_env_${git_version}_$(date +%F_%T)_install.log"

prefix=${prefix:-/fastdata/bm1235/python_environments}
name=${name:-hamburg-hackathon}

if [ ! -d  ${prefix}/miniconda3 ] ; then
mkdir -p ${prefix}/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ${prefix}/miniconda3/miniconda.sh
bash ${prefix}/miniconda3/miniconda.sh -b -u -p ${prefix}/miniconda3
rm -f ${prefix}/miniconda3/miniconda.sh
fi


command="${prefix}/miniconda3/bin/conda env create --file environment.yaml --prefix ${prefix}/${name}"
echo $command > ${logname}
echo >> ${logname}

$command >>${logname} 2>&1
cp  install_kernel ${prefix}/${name}/bin/


# -freeze-installed, --no-update-deps

